In [1]:
import numpy as np

### 从python列表生成一维数组

In [2]:
list_of_ints = [1, 2, 3]
Array_1 = np.array(list_of_ints)
Array_1

array([1, 2, 3])

In [3]:
Array_1[1]

2

In [4]:
type(Array_1)

numpy.ndarray

In [5]:
Array_1.dtype

dtype('int64')

### 控制内存大小

In [6]:
Array_1.nbytes

24

In [7]:
Array_1 = np.array(list_of_ints, dtype='int8')
Array_1.nbytes

3

In [8]:
# 也可以改变数据类型，使用astype创建一个新的数组
Array_1b = Array_1.astype('float32')
Array_1b

array([ 1.,  2.,  3.], dtype=float32)

### 使用异构类型生成np列表

In [10]:
complex_list = [1, 2, 3] + [1., 2., 3.] + ['a', 'b', 'c']
Array_2 = np.array(complex_list[:3])
print 'complext_list[:3]', Array_2.dtype

Array_2 = np.array(complex_list[:6])
print 'complext_list[:6]', Array_2.dtype

Array_2 = np.array(complex_list)
print 'complext_list[:]', Array_2.dtype

print isinstance(Array_2[0], np.number)

complext_list[:3] int64
complext_list[:6] float64
complext_list[:] |S32
False


### 多维数组

In [11]:
a_list_of_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
Array_2D = np.array(a_list_of_list)
Array_2D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
Array_2D[1, 1]

5

In [13]:
a_list_of_list_of_list = [[[1,2], [3,4], [5,6]], [[7,8], [9,10],[11,12]]]
Array_3D = np.array(a_list_of_list_of_list)
Array_3D

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [14]:
Array_3D[0,2,0]

5

In [15]:
# 可以使用元组创建数组，使用.items()方法将字典转变成二维数组
np.array({1:2, 3:4, 5:6}.items())

array([[1, 2],
       [3, 4],
       [5, 6]])

### 改变数组大小

In [22]:
original_array = np.array([1, 2, 3, 4, 5, 6, 7, 8])
Array_a = original_array.reshape(4,2)
Array_b = original_array.reshape(4,2).copy()
# .copy()创建新的数组，其余的方式都是改变数组的view方式
Array_c = original_array.reshape(2, 2, 2)
original_array[0] = -1

In [23]:
Array_a

array([[-1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8]])

In [24]:
Array_b

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [25]:
Array_c

array([[[-1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]]])

In [27]:
#使用.shape()方法也能得到相同的结果
original_array.shape = (4,2)
original_array

array([[-1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8]])

### 使用函数生成数组

In [29]:
ordinal_values = np.arange(9).reshape(3,3)
ordinal_values

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [30]:
# 可以使用[::-1]颠倒顺序
ordinal_values = np.arange(9)[::-1].reshape(3,3)
ordinal_values

array([[8, 7, 6],
       [5, 4, 3],
       [2, 1, 0]])

In [34]:
# 可以使用随机整数产生数组
np.random.randint(low=1, high=10, size=(3,3)).reshape(3,3)

array([[8, 7, 9],
       [1, 8, 8],
       [6, 2, 9]])

In [35]:
# 全零
np.zeros((3,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [36]:
#全1
np.ones((3,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [38]:
#单位矩阵
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [39]:
# 等差数列
np.linspace(start=0, stop=1, num=10)

array([ 0.        ,  0.11111111,  0.22222222,  0.33333333,  0.44444444,
        0.55555556,  0.66666667,  0.77777778,  0.88888889,  1.        ])

In [40]:
# 等比数列
np.logspace(start=0, stop=1, num=10, base=10.0)

array([  1.        ,   1.29154967,   1.66810054,   2.15443469,
         2.7825594 ,   3.59381366,   4.64158883,   5.9948425 ,
         7.74263683,  10.        ])

In [41]:
# 生成标准正态分布的3*3矩阵
np.random.normal(size=(3, 3))

array([[ 1.14111551, -2.45644371,  0.73056955],
       [ 0.09875287,  0.14087513, -0.22817862],
       [ 1.42772167, -1.1451913 ,  1.43374792]])

In [42]:
# 可以指定不同的均值和标准差，loc表示均值，scale表示标准差
np.random.normal(loc=1.0, scale=3.0, size=(3,3))

array([[-0.82767426, -5.0906003 , -1.94872193],
       [ 0.25555235,  0.93765952,  1.85926278],
       [ 1.48333425,  0.74834042,  3.70498425]])

In [43]:
# 生成均匀分布的3*3矩阵
np.random.uniform(low=0.0, high=1.0, size=(3,3))

array([[ 0.84988148,  0.94972665,  0.2043008 ],
       [ 0.95536784,  0.56150303,  0.47942664],
       [ 0.75708271,  0.81254002,  0.06501106]])

#### 直接从文件中获得数组

In [47]:
# loadtxt需要指定文件名、分隔符和数据类型，如果dtype有误，则无法加载
housing = np.loadtxt('regression-datasets-housing.csv', delimiter=',', dtype=float)
housing

array([[  6.32000000e-03,   1.80000000e+01,   2.31000000e+00, ...,
          3.96900000e+02,   4.98000000e+00,   2.40000000e+01],
       [  2.73100000e-02,   0.00000000e+00,   7.07000000e+00, ...,
          3.96900000e+02,   9.14000000e+00,   2.16000000e+01],
       [  2.72900000e-02,   0.00000000e+00,   7.07000000e+00, ...,
          3.92830000e+02,   4.03000000e+00,   3.47000000e+01],
       ..., 
       [  6.07600000e-02,   0.00000000e+00,   1.19300000e+01, ...,
          3.96900000e+02,   5.64000000e+00,   2.39000000e+01],
       [  1.09590000e-01,   0.00000000e+00,   1.19300000e+01, ...,
          3.93450000e+02,   6.48000000e+00,   2.20000000e+01],
       [  4.74100000e-02,   0.00000000e+00,   1.19300000e+01, ...,
          3.96900000e+02,   7.88000000e+00,   1.19000000e+01]])